version: '3.4'

services:
    postgres:
        build:
            context: .
            target: postgres
        ports:
            - "5432:5432"
        container_name: postgres-dev
        environment:
            - POSTGRES_DB=workspace
            - POSTGRES_USER=postgres
            - PGUSER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST_AUTH_METHOD=trust
            - PGGSSENCMODE=disable
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - "./dbdata:/var/lib/postgresql/data"
    dev:
        build:
            context: .
            target: nestjs-dev
        container_name: server-dev
        ports:
            - "3000:3000"
        environment:
            - ENV=dev
        volumes:
            - "./:/usr/src/app/"
        command: "yarn run start:dev"
        depends_on:
            postgres:
                condition: service_healthy
